# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_post_exposed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exposed',
            field=models.BooleanField(default=False, help_text='Should the post be shown on the front page'),
        ),
    ]
