# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20171210_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='exposed',
            field=models.BooleanField(default=False, help_text='Should the post be shown on the front page', verbose_name='Vidno na prvi strani'),
        ),
    ]
