# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 16:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20171210_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 10, 17, 30, 38, 965920)),
            preserve_default=False,
        ),
    ]
