# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_show_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='show',
            name='show_title',
        ),
    ]
