# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-10 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20171210_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='', help_text='Prvi odstavek in povzetek', verbose_name='Povzetek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(verbose_name='Besedilo'),
        ),
    ]
