# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_showindex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='cover',
            new_name='main_cover',
        ),
    ]
